table ProductsTable
	lineageTag: fe4e0bb2-d5c6-4e25-95ee-172f493f2656

	column Product_ID
		dataType: string
		lineageTag: c90f4cfc-ca42-4f0d-ad43-f32de0ad6939
		summarizeBy: none
		sourceColumn: Product_ID

		annotation SummarizationSetBy = Automatic

	column Product_Name
		dataType: string
		lineageTag: 76628f48-79fa-41cd-b851-069a2ad8cce3
		summarizeBy: none
		sourceColumn: Product_Name

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 60a53b92-c6e1-47d5-9022-93af7353c6c5
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Subcategory
		dataType: string
		lineageTag: 2fffd88e-6156-4548-b249-8b2d481a6749
		summarizeBy: none
		sourceColumn: Subcategory

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: 1d55f8cf-788a-4489-a08e-2dc50881621a
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Supplier
		dataType: string
		lineageTag: e399cc6e-474e-4f79-a705-304a7b54e74d
		summarizeBy: none
		sourceColumn: Supplier

		annotation SummarizationSetBy = Automatic

	column Launch_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b894e27d-9bb7-42d9-9504-15a09df0b36f
		summarizeBy: none
		sourceColumn: Launch_Date

		variation Variation
			isDefault
			relationship: c1417657-a703-4216-b335-f1996503bf32
			defaultHierarchy: LocalDateTable_1e5b2d8f-86ff-4b44-8125-f33c984a499b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column List_Price
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a8083208-bcec-4ebe-9dba-c86df4e24d85
		summarizeBy: sum
		sourceColumn: List_Price

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Standard_Cost
		dataType: int64
		formatString: 0
		lineageTag: 8070d072-55dc-4409-b51c-34a5cadeb2bd
		summarizeBy: sum
		sourceColumn: Standard_Cost

		annotation SummarizationSetBy = Automatic

	column Product_Status
		dataType: string
		lineageTag: de359615-360f-46ba-9358-674ee7ba8156
		summarizeBy: none
		sourceColumn: Product_Status

		annotation SummarizationSetBy = Automatic

	partition ProductsTable = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("Y:\Desktop\Project_DA\Retail Dataset.xlsx"), null, true),
				    ProductsTable_Table = Source{[Item="ProductsTable",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(ProductsTable_Table,{{"Product_ID", type text}, {"Product_Name", type text}, {"Category", type text}, {"Subcategory", type text}, {"Brand", type text}, {"Supplier", type text}, {"Launch_Date", type date}, {"List_Price", Int64.Type}, {"Standard_Cost", Int64.Type}, {"Product_Status", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

