table CustomersTable
	lineageTag: 518703c1-2af4-4279-9ee1-6082f85d6a56

	column Customer_ID
		dataType: string
		lineageTag: 22b7d58e-20b6-467b-9c80-93f5f6823a33
		summarizeBy: none
		sourceColumn: Customer_ID

		annotation SummarizationSetBy = Automatic

	column Join_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d7a9f74a-ada1-4a4f-9ce1-20fd142d5e6a
		summarizeBy: none
		sourceColumn: Join_Date

		variation Variation
			isDefault
			relationship: da114dd3-0020-404b-ab44-0c7cdad2c927
			defaultHierarchy: LocalDateTable_014feec3-aa67-475a-8c35-d646bbb27052.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Age_Group
		dataType: string
		lineageTag: ae86415a-caa6-4e4a-9e86-7dbdb7fab3b4
		summarizeBy: none
		sourceColumn: Age_Group

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: a3b7cef6-980a-4707-adc2-f12a0141bdd7
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 1b84430d-0145-4df8-8e51-ff28a6f8ede1
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 47e86551-edad-47e9-8840-29123d478411
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Member_Tier
		dataType: string
		lineageTag: d225f1eb-2faf-4024-bb73-afe9102b8e5a
		summarizeBy: none
		sourceColumn: Member_Tier

		annotation SummarizationSetBy = Automatic

	column Acquisition_Source
		dataType: string
		lineageTag: f5c9c693-0b5b-4440-ad93-3d9de2e8ccad
		summarizeBy: none
		sourceColumn: Acquisition_Source

		annotation SummarizationSetBy = Automatic

	column Preferred_Channel
		dataType: string
		lineageTag: 9c4a1276-f381-495c-bc1e-73e6f892e22f
		summarizeBy: none
		sourceColumn: Preferred_Channel

		annotation SummarizationSetBy = Automatic

	partition CustomersTable = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("Y:\Desktop\Project_DA\Retail Dataset.xlsx"), null, true),
				    CustomersTable_Table = Source{[Item="CustomersTable",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(CustomersTable_Table,{{"Customer_ID", type text}, {"Join_Date", type date}, {"Age_Group", type text}, {"Gender", type text}, {"City", type text}, {"Region", type text}, {"Member_Tier", type text}, {"Acquisition_Source", type text}, {"Preferred_Channel", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

